### ISSUE TITLE
What is the minimum SETS value?

### ISSUE THREAD

**Issue by dlangille** [mkjail/mkjail#11]
This code seems to indicate that is "base lib32 src".

Is that correct?

https://github.com/mkjail/mkjail/blob/cdf76b58f0a717ef853cd174ac2d952f339d640e/src/share/mkjail/upgrade.sh#L86-L88

**Comment by dlangille** [comment]
I have been using this patch recently.

```
index 481da6c..7918117 100755
--- a/src/share/mkjail/upgrade.sh
+++ b/src/share/mkjail/upgrade.sh
@@ -83,9 +83,9 @@ _validate()
     export MKJAILVER="$(zfs get -H mkjail:version ${JAILROOT}/${JAILNAME} | awk '{print $3}')"
 
     # Check if we have the sets for the target version we are upgrading to
-    [ -f /var/db/mkjail/releases/${ARCH}/${TARGETVER}/base.txz ] || _getrelease
-    [ -f /var/db/mkjail/releases/${ARCH}/${TARGETVER}/lib32.txz ] || _getrelease
-    [ -f /var/db/mkjail/releases/${ARCH}/${TARGETVER}/src.txz ] || _getrelease
+    for DIST in $(echo "${SETS}"); do
+      [ -f /var/db/mkjail/releases/${ARCH}/${TARGETVER}/${DIST}.txz ]  || _getrelease
+    done
     [ -d ${SRCPATH} ] || _getrelease
 }
 
[dvl@r720-02:~/src/mkjail] $ 

```

**Comment by feld** [comment]
Yeah I saw this too and just forced lib32 to always be there in !34 because if we try to upgrade a jail that was originally built with lib32 we detect that and intelligently use the lib32.txz set, but rollback the upgrade if lib32.txz isn't available. So it simply must be available at all times.
