### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by clausecker** [mkjail/mkjail#16]
Greetings!

As requested on the [WantedPorts](https://wiki.freebsd.org/WantedPorts) page, I would like to make a port for this project.  Unfortunately, no version is tagged in this repository and I do not really want to package a random possibly unstable project state.

Please tag a release if possible so I can base the port on that release and version number.

**Comment by dlangille** [comment]
I just created 0.0.1

Thank you for maintaining the port.

**Comment by dlangille** [comment]
This is as stable as recent. If you hit issues in porting, please let us know. One issue: the .conf file. That really should be in ‘/usr/local/etc/mkjail’ and a port might be the push we need to change the code.  Unless you can patch it in the port.

**Comment by clausecker** [comment]
If I understood the logic in `src/bin/mkjail` correctly, the configuration file is fetched from the same prefix as the script, so if the script is in `/usr/local`, the correct configuration file is used already.

Would you mind writing a `pkg-descr` file for the port?  I'm not super familiar with this port's features, so if you write the description, it'll probably be a lot better than if I attempted to do it.

**Comment by dlangille** [comment]
I have added information to the README.md, how's that?

**Comment by clausecker** [comment]
Thanks for the quick response!

Port submitted in [PR #256871](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256871).  Someone please edit the [WantedPorts](https://wiki.freebsd.org/WantedPorts) page to take out this one.
