### ISSUE TITLE
JAILROOT and creation

### ISSUE THREAD

**Issue by grahamperrin** [mkjail/mkjail#17]
If `JAILROOT="/copperbowl/iocage/jails"` then why is creation at a different path?

(Do I misunderstand?)

```text
root@mowa219-gjp4-8570p:~ # mkjail create -j 13 -v 13.0-RELEASE
Creating copperbowl/jails/13...
Extracting base into /copperbowl/iocage/jails/13...
tar: could not chdir to '/copperbowl/iocage/jails/13'

root@mowa219-gjp4-8570p:~ # grep JAILROOT /usr/local/etc/mkjail.conf
JAILROOT="/copperbowl/iocage/jails"
root@mowa219-gjp4-8570p:~ # mount | grep jails
copperbowl/poudriere/jails/main on /usr/local/poudriere/jails/main (zfs, local, noatime, nfsv4acls)
copperbowl/poudriere/jails on /copperbowl/poudriere/jails (zfs, local, noatime, nfsv4acls)
copperbowl/iocage/jails on /copperbowl/iocage/jails (zfs, local, noatime, nfsv4acls)
copperbowl/iocage/jails/jbrowsers on /copperbowl/iocage/jails/jbrowsers (zfs, local, noatime, nfsv4acls)
copperbowl/iocage/jails/jbrowsers/root on /copperbowl/iocage/jails/jbrowsers/root (zfs, local, noatime, nfsv4acls)
copperbowl/jails on /jails (zfs, local, noatime, nfsv4acls)
copperbowl/jails/13 on /jails/13 (zfs, local, noatime, nfsv4acls)
root@mowa219-gjp4-8570p:~ # uname -KrU
14.0-CURRENT 1400025 1400025
root@mowa219-gjp4-8570p:~ # 
```

**Comment by grahamperrin** [comment]
Also (after editing my configuration file) is there a mount point issue? 

```text
root@mowa219-gjp4-8570p:~ # nano /usr/local/etc/mkjail.conf
root@mowa219-gjp4-8570p:~ # uname -KrU
14.0-CURRENT 1400025 1400025
root@mowa219-gjp4-8570p:~ # mkjail create -j 13 -v 13.0-RELEASE
Creating copperbowl/jails/13...
Extracting base into /copperbowl/jails/13...
tar: could not chdir to '/copperbowl/jails/13'

root@mowa219-gjp4-8570p:~ # mount | grep 13
copperbowl/jails/13 on /jails/13 (zfs, local, noatime, nfsv4acls)
root@mowa219-gjp4-8570p:~ # grep JAILROOT /usr/local/etc/mkjail.conf
JAILROOT="/copperbowl/jails"
root@mowa219-gjp4-8570p:~ # 
```

**Comment by dlangille** [comment]
First, I wouldn't mix `mkjail` with`iocage`.

Let's confirm `/usr/local/etc/mkjail.conf` is being used.

Looking at https://github.com/mkjail/mkjail/blob/master/src/bin/mkjail#L59 

Try putting an echo in your `.conf` file and an exit. If that doesn't help, try `echo $JAILROOT` around line 82 of `mkjail`.

I'm not the port maintainer and I haven't had a chance to use the port yet.

**Comment by grahamperrin** [comment]
Thanks, 

> echo `$JAILROOT` around line 82 of `mkjail`.

```text
root@mowa219-gjp4-8570p:~ # mkjail create -j 12 -v 12.0-RELEASE
/copperbowl/iocage/jails
Release 12.0-RELEASE does not exist. Attempting to fetch...
Fetching release manifest...
MANIFEST                                              1045  B   13 MBps    00s
Fetching release tarballs...
base.txz                                               147 MB 8242 kBps    19s
lib32.txz                                               58 MB 7777 kBps    08s
src.txz                                                152 MB 8438 kBps    18s
base.txz: sha256 verified
lib32.txz: sha256 verified
src.txz: sha256 verified
Extracting src for use in jail upgrades...
Creating copperbowl/jails/12...
Extracting base into /copperbowl/iocage/jails/12...
tar: could not chdir to '/copperbowl/iocage/jails/12'

root@mowa219-gjp4-8570p:~ # 
```

> I'm not the port maintainer and I haven't had a chance to use the port yet.

OK, I'll aim for Bugzilla `sysutils/mkjail` if there's any future issue. 

The simplicity that it brings to jails is **very** appealing. <https://forums.FreeBSD.org/threads/80117/post-523344> I shared my first experiences with the port. 

----

Side note: I aimed for a path that included `/iocage/` for test purposes, because it existed (not because I'm an active user of iocage; I removed the software so long ago, I have no idea how to use it). 

Thanks for the hint.

**Comment by dlangille** [comment]
I'm trying to get `bhyve` configured for a test environment.

**Comment by fyfe** [comment]
> 
> 
> Also (after editing my configuration file) is there a mount point issue?
> 
> ```
> root@mowa219-gjp4-8570p:~ # nano /usr/local/etc/mkjail.conf
> root@mowa219-gjp4-8570p:~ # uname -KrU
> 14.0-CURRENT 1400025 1400025
> root@mowa219-gjp4-8570p:~ # mkjail create -j 13 -v 13.0-RELEASE
> Creating copperbowl/jails/13...
> Extracting base into /copperbowl/jails/13...
> tar: could not chdir to '/copperbowl/jails/13'
> 
> root@mowa219-gjp4-8570p:~ # mount | grep 13
> copperbowl/jails/13 on /jails/13 (zfs, local, noatime, nfsv4acls)
> root@mowa219-gjp4-8570p:~ # grep JAILROOT /usr/local/etc/mkjail.conf
> JAILROOT="/copperbowl/jails"
> root@mowa219-gjp4-8570p:~ # 
> ```

@grahamperrin it's a config issue, from the output of `mount` you're `mkjail.conf` should be:
```bash
ZPOOL="copperbowl"
JAILROOT="jails"
```

**Comment by fyfe** [comment]
Also take not of the limitation mentioned in #18

**Comment by dlangille** [comment]
> Also take not of the limitation mentioned in #18

@grahamperrin for now, use JAILROOT="jails"

**Comment by dlangille** [comment]
I think this is now fixed with the current code. A port update will follow. If the problem persists, please reopen.

**Comment by grahamperrin** [comment]
Thanks
