### ISSUE TITLE
create fails if JAILROOT != /jails

### ISSUE THREAD

**Issue by fyfe** [mkjail/mkjail#18]
https://github.com/mkjail/mkjail/blob/79b4c0316816823aa137f93706d5f794a50eb4fd/src/share/mkjail/create.sh#L83-L86

If `JAILROOT` isn't set to `/jails` create will fail as the dataset path is hardcoded.

**Comment by dlangille** [comment]
Nasty!

I'll get this fixed and tested as soon as I can get my testing environment working.

**Comment by dlangille** [comment]
I've not forgotten this. I have a test environment created.
