### ISSUE TITLE
upgrade does not check SETS when checking for required files

### ISSUE THREAD

**Issue by dlangille** [mkjail/mkjail#7]
see https://github.com/mkjail/mkjail/blob/master/src/share/mkjail/upgrade.sh#L86

If SET contains only src, it should check only `base.txz`

I think this is the fix:

```
    # Check if we have the sets for the target version we are upgrading to
    for set in $SETS
    do
        [ -f /var/db/mkjail/releases/${ARCH}/${TARGETVER}/${set}.txz ] || _getrelease
    done

```

**Comment by dlangille** [comment]
But wait, there's more:

`tar: Error opening archive: Failed to open '/var/db/mkjail/releases/amd64/12.2-RELEASE/lib32.txz'`

Tracking that one down now.

**Comment by dlangille** [comment]
Oh, it seems like there really is a /usr/lib32 in my jails.  I need to add that to SETS

**Comment by dlangille** [comment]
QUESTION: why does `getrelease` need `-s` when we have `SETS`?

**Comment by dlangille** [comment]
I did have to interact with the keyboard during this phase:

```
The following files will be updated as part of updating to
12.2-RELEASE-p2:
/bin/freebsd-version
/lib/libcrypto.so.111
```

Pressing `q` allowed the upgrade to install.

**Comment by dlangille** [comment]
I saw this for some of the pkg upgrades:

```
[ingress01] [18/155] Extracting libunistring-0.9.10_1: 100%
/bin/sh: indexinfo: not found
pkg-static: POST-INSTALL script failed
[ingress01] [19/155] Reinstalling libtasn1-4.16.0...
[ingress01] [19/155] Extracting libtasn1-4.16.0: 100%
/bin/sh: indexinfo: not found
pkg-static: POST-INSTALL script failed
[ingress01] [20/155] Upgrading libassuan from 2.5.3 to 2.5.4...
[ingress01] [20/155] Extracting libassuan-2.5.4: 100%
/bin/sh: indexinfo: not found
pkg-static: POST-INSTALL script failed
[ingress01] [21/155] Upgrading glib from 2.66.0_1,1 to 2.66.4,1...
[ingress01] [21/155] Extracting glib-2.66.4,1: 100%
```

**Comment by dlangille** [comment]
jails upgraded.

**Comment by dlangille** [comment]
I see that I am doing nothing wrong, yet it insists:

```
[root@r720-02:/home/dvl/src/mkjail] # ./src/bin/mkjail getrelease -s base -v 12.2-RELEASE
Both -s and -v must be specified.

usage: mkjail getrelease [-s "SETS"] [-v VERSION]

        -s Sets: "base doc games lib32"
        -v Version of jail (9.3-RELEASE, 10.1-RELEASE, etc)

mkjail.sh: 2019, feld@FreeBSD.org

[root@r720-02:/home/dvl/src/mkjail] # ./src/bin/mkjail getrelease -s "base src lib32" -v 12.2-RELEASE
Both -s and -v must be specified.

usage: mkjail getrelease [-s "SETS"] [-v VERSION]

        -s Sets: "base doc games lib32"
        -v Version of jail (9.3-RELEASE, 10.1-RELEASE, etc)

mkjail.sh: 2019, feld@FreeBSD.org

[root@r720-02:/home/dvl/src/mkjail] # 

```

**Comment by dlangille** [comment]
See #6 where much of this is covered.

**Comment by dlangille** [comment]
> see https://github.com/mkjail/mkjail/blob/master/src/share/mkjail/upgrade.sh#L86
> 
> If SET contains only src, it should check only `base.txz`
> 
> I think this is the fix:
> 
> ```
>     # Check if we have the sets for the target version we are upgrading to
>     for set in $SETS
>     do
>         [ -f /var/db/mkjail/releases/${ARCH}/${TARGETVER}/${set}.txz ] || _getrelease
>     done
> ```

I'm upgrading the jails on my `knew` server without this patch and with `SETS="base lib32"`

**Comment by feld** [comment]
also related to #34
