### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by wwparker** [mkjail/mkjail#8]
In step 2 of the instructions, it is missing the l in mkjail.

./src/bin/mkjai create -v 10.3-RELEASE -j testjail -f default

should be

./src/bin/mkjail create -v 10.3-RELEASE -j testjail -f default

**Comment by dlangille** [comment]
Nice catch.

I had fixed this over at https://git.langille.org/dvl/mkjail and pulled it in from there.  Thank you.
